#!/usr/bin/env node

require('babel-core/register');
require('babel-polyfill');

// # Define global class-helpers for more flexible imports and usages
global.util = require('../utils');

// # ===================================================================================================================

const config = require('../apps/main/config/config');
const port = config.server.port;
const mainApp = config.server.apps.main_path;

const app = require(mainApp);
const http = require('http');

// # ===================================================================================================================

const server = http.createServer(app);

server.listen(port);

// # ===================================================================================================================

const onError = require('./lib').onError;
const onListening = require('./lib').onListening;

server.on('error', onError);
server.on('listening', onListening);

// # ===================================================================================================================
